// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// RMPSS_opt
NumericVector RMPSS_opt(NumericVector x0, Function func, double s_init, double no_runs, double max_iter, double rho_1, double rho_2, double phi, double lambda, double tol_fun, double tol_fun_2, int print_output);
RcppExport SEXP _RMPSS_RMPSS_opt(SEXP x0SEXP, SEXP funcSEXP, SEXP s_initSEXP, SEXP no_runsSEXP, SEXP max_iterSEXP, SEXP rho_1SEXP, SEXP rho_2SEXP, SEXP phiSEXP, SEXP lambdaSEXP, SEXP tol_funSEXP, SEXP tol_fun_2SEXP, SEXP print_outputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< Function >::type func(funcSEXP);
    Rcpp::traits::input_parameter< double >::type s_init(s_initSEXP);
    Rcpp::traits::input_parameter< double >::type no_runs(no_runsSEXP);
    Rcpp::traits::input_parameter< double >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type rho_1(rho_1SEXP);
    Rcpp::traits::input_parameter< double >::type rho_2(rho_2SEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type tol_fun(tol_funSEXP);
    Rcpp::traits::input_parameter< double >::type tol_fun_2(tol_fun_2SEXP);
    Rcpp::traits::input_parameter< int >::type print_output(print_outputSEXP);
    rcpp_result_gen = Rcpp::wrap(RMPSS_opt(x0, func, s_init, no_runs, max_iter, rho_1, rho_2, phi, lambda, tol_fun, tol_fun_2, print_output));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RMPSS_RMPSS_opt", (DL_FUNC) &_RMPSS_RMPSS_opt, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_RMPSS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
