# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RMPSS_opt <- function(x0, func, s_init = 1, no_runs = 1000, max_iter = 10000, rho_1 = 2, rho_2 = 2, phi = 10^(-20), lambda = 10^(-10), tol_fun = 10^(-6), tol_fun_2 = 10^(-20), print_output = 0L) {
    .Call(`_RMPSS_RMPSS_opt`, x0, func, s_init, no_runs, max_iter, rho_1, rho_2, phi, lambda, tol_fun, tol_fun_2, print_output)
}

